### ISSUE TITLE
Private Cloud Music API struct (Chinese)

### ISSUE THREAD

**Issue by BLumia** [BLumia/Private-Cloud-Music#6]
# Private Cloud Music API 结构说明 征求意见稿

## 设计理念和简要说明

Private Cloud Music (以下简称PCM) 设计上最初是为了便于可以极度方便快速的部署自己的在线私有云音乐播放 web-app ，而日常使用有了一些新的需求，于是希望有个确定且合理的 API 结构，以便日后修改和使用。新的需求大概如下：

 - 确立一套明确的API标准，可将一个 PCM API 地址作为一个“源”使用。
 - 为了保持任何步骤都足够简单，不能使用影响简易使用的程度的技术。
 - 对于文件夹形式的结构，可能需要允许支持子文件夹。
 - 可能需要支持文件上传和文件夹管理
 - 可以开发便于使用的客户端
 - 允许绝对的私有

### 可将 PCM API 地址作为一个“源”使用

可能有更多人使用且希望分享自己的云音乐给同样在使用这个应用的人，如果具备一个统一的“协议”，那么就可以将私有云音乐功能作为一个“源”来使用。另一方面，计划有开发一个通用的客户端便于用户使用，用户只要使用或兼容 PCM API 就可以直接使用客户端访问和使用自己的云音乐，于是需要确立一套明确的API标准。

### 保持简单

尽可能保持使用上的简单（Simple & Stupid），如此做会牺牲掉一些本身更惯用的做法。比如没有选则正宗的RESTful，使用 url 路由以避免需要额外的设置htaccess重定向，以及 web-app 的前端只使用了 Plain-JS 等。

因为设计上本身是以 API 为主的，尽量简单的 API 以便用户可以非常快速的使用其它语言实现对 PCM API 的支持而不仅仅局限于现有的 php 版本后端，于是 API 在设计上本身也应该在保持合理的情况下保持简单。

### 支持子文件夹

现有的版本只支持一层文件夹内的所有文件夹作为播放列表，而播放列表内如果存在子文件夹则直接忽略。虽然设计上本身是不允许扫子文件夹作为列表的（文件名即唯一键），但实际支持子文件夹似乎也是个不错的主意，待考虑。

### 文件上传和文件夹管理

如果开发客户端，文件上传和文件管理的确可以方便的省去每次都开 scp/ftp 上传管理文件的事。但如果用户本身不是源的所有者，应该不允许文件管理操作。如果实现，会通过密码参数区别。但对于基本的客户端，文件管理相关的 API 应该是可选实现的（作为存粹的源的“阅读”器）。

### 便于开发客户端

客户端本身为了解决用户每次都需要重新去服务器刷新和下载乐曲文件的问题，以便脱机工作。也可以增加文件管理和本地列表创建（播放列表不同于服务器端的文件夹内的文件列表）等特性以便于使用。另外需要确定 API 的合理性以便更新不会导致 API 变动而使得旧的源失效。另外， API 设计上也应该具备可拓展性以便于用户自身的需求，但基本功能的 API 应该一致。

### 允许绝对私有

因为是私有云音乐，或许有得用户不希望所有人都能看到里面的内容，于是可以允许用户访问云音乐时输入密码，如果正确才能加载列表使用功能。

### 基本API内容

现有的 API 使用一个接口处理所有的行为请求，使用 `do` 参数区别行为并做出响应。

任何 PCM API 兼容的后端实现应该至少兼容基本 API 内容。

作为最基础的功能， *取得文件夹列表* 和 *取得文件夹内的音频文件列表* 应该为 PCM 的最根本的 API 。分别为：

#### 取得文件夹列表:

参数 | 值
------|---
do | getfolders 

返回：

``` json
{
	"status": 200,
	"message": "OK",
	"result":{
		"type": "folderList",
		"data": [
			"Folder1", "Folder2", "Folder3"
		]
	}
}
```

#### 取得文件夹内的音频文件列表

参数 | 值
------|---
do | getplaylist
folder | 文件夹名称(uriencoded string, end with '/')

返回：

``` json
{
	"status": 200,
	"message": "OK",
	"result":{
		"type": "fileList",
		"data": [
			{
				"fileName": "FileName.mp3",
				"fileSize": 123123123,
				"modifiedTime": "1313065072"
			},
			{
				"fileName": "FileName2.wav",
				"fileSize": 123123123,
				"modifiedTime": "1313065072"
			}
		]
	}
}
```

待议：
(?) 对于多层文件夹，允许传递 “Folder/Subfolder/” 获得子文件夹的内容
(?) 返回的值应当怎样呈现该路径下存在的子文件夹和音频文件（对于`getplaylist`请求的响应是否合理）？
(?) 允许绝对私有的情况下，是否应当对于每个请求都传递一个 `password` （或叫 `token`） 参数?

### 扩展API内容

扩展 API 可以选择被实现或否， API 内容不影响最基础功能的使用。

以下 API 暂时均未且暂不打算在 v1 版本的php实现中实现。

#### 文件夹创建

参数 | 值
------|---
do | creatfolder
folder | 文件夹名称(uriencoded string, end with '/')

#### 文件上传

参数 | 值
------|---
do | upload
folder | 文件夹名称(uriencoded string, end with '/')
file | 要上传的文件

#### 文件删除

参数 | 值
------|---
do | remove
folder | 文件夹名称(uriencoded string, end with '/')
filename | 要删除的文件名称(uriencoded string)

(?) 是否应该具备一个 API 查询该实现对 PCM API 的支持情况，比如当前API兼容的版本，是否支持文件管理等扩展API。
(?) 这些扩展 API 是否合理，应当怎样响应这些请求。

### 作为源

作为源，应该以怎样的形式允许添加源更合理？预想必须包含的信息内容可能有：

 - 源地址（处理所有请求的API地址）
 - 密码（本地维护，用于请求时传递）
 - API版本（便于兼容判断 ?）
 - 扩展API支持情况（是否与上一条重复？）

**Comment by chirs241097** [comment]
因为没什么Web应用开发经验……只提出几个可能需要解决的问题：

- 如果不希望浪费空间，某个曲目同时属于多个播放列表/文件夹的情况应如何处理？
- getplaylist返回的result类型为fileList，是要直接将文件夹视作播放列表吗？
- 可否考虑允许普通用户（具有访问权限而无上传权限）根据已有文件创建自己的播放列表？

Chris X.

**Comment by BLumia** [comment]
> 某个曲目同时属于多个播放列表/文件夹的情况应如何处理？

符号链接应该可以解决，然后照常处理即可

> 是要直接将文件夹视作播放列表吗？

原本为了保持简单而没考虑使用数据库维护播放列表，后来也有考虑以文本文件（当时写的时候维护的是个json）存储播放列表清单和播放列表。不过每次更新文件后都需要重新手动维护这些列表，于是最终选择的是直接以文件夹形式呈现所有关系。当然，缺点就是上面那一条了，重复曲目较多的话符号链接的确会搞得麻烦一些。

> 可否考虑允许无上传权限的用户根据已有文件创建自己的播放列表？

原本只考虑了客户端允许创建播放列表（区别于服务器硬点的文件列表和结构，以及允许列表的曲目跨“源”使用），尚不清楚html5标准是否允许站点在本地长期的保存文件（用于存储用户自己的播放列表）。如果实现应该也是前端实现，可以确定的是， API 后端应该不会提供这个功能，虽然用户可以自己拓展。

**Comment by BLumia** [comment]
对于子文件夹的支持，把 `getplaylist` 改成如此返回不知是否合适

``` json
{
  "status": 200,
  "message": "OK",
  "result": {
    "type": "fileList",
    "data": {
      "musicList": [
        {
          "fileName": "example.mp3",
          "fileSize": 5418885,
          "modifiedTime": 1484062662
        }
      ],
      "subFolderList": [
        "test", "test2"
      ]
    }
  }
}
```

存在的问题：
 - 如果获取播放列表也会返回请求路径下存在的文件夹，那和获取文件夹列表的功能似乎可以算作重复？
 - 实现方面，奇怪字符集系统下的多重子文件夹编码问题如何解决？

@chirs241097 @instr3

**Comment by jxpxxzj** [comment]
关于 API 参数传递: 
目前 Issue 写的传递方式不明确, 目前实现的 php 后端是使用 & 拼接参数 ( ```do=getplaylist&folder=/``` )
建议方式是把参数序列化成 json 后放进 body 里再 POST 给 API, 这样会更直观, 如下所示:
```
{
    "do": "getplaylist",
    "folder": "/"
}
```
参考微信公众平台的实现 [微信公众平台](https://mp.weixin.qq.com/wiki)

**Comment by BLumia** [comment]
当前认为存在的问题：

 - 子目录列表是 `string[]`，并且直接对应路径，如果真实对应子目录就要写全路径，显示会很难看，另一方面目前的结构无法做到路径和显示文字不同的需求，可以调整为和 `musicList` 中项目近似的结构。
 - 设计初期 API 是参照文件系统的结构思考的，尽管目前的 API 结构实际可以做到让其和服务端存储文件的结构和方式完全无关，但 API 中属性名字的语义还是和原本的思想关联的，或许可以考虑调整（`subFolderList`->`subPlaylists`）。
 - `fileName` 是钦定当前路径下访问这个音频文件的方式，“某个曲目同时属于多个播放列表/文件夹”的需求尽管可以以软连接的形式解决（最懒的办法），但也应该考虑从 API 上解决这个问题。

**Comment by BLumia** [comment]
尽管目前设计目的上即希望文件可以直接以文件系统目录结构形式直接存储，但考虑到可能存在其它需求，例如 m3u8 ts 音频串流，选择音频质量等潜在需求存在，目前的 API 设计还是不理想，随后可能根据需求重新考量。暂时关闭 Issue。
